<a href="https://www.kaggle.com/edwardakalarrywelch/very-basic-numpy-notes?scriptVersionId=87571317" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Very Basic Numpy Notes

In [ ]:
#import numpy as np
import numpy as np
import math

# How to make a numpy array.

In [ ]:
# Use a list to create an array.
array_one = np.array([1, 2, 3])
print(array_one)

# print number of dimensions of a list using ndim.
print(array_one.ndim)

# Below, we create a 2X3 multi-dimensional array.

In [ ]:
# Create a multi-dimensional array from a list of lists.
array_two_by_three = np.array([[1,2,3],[4,5,6]])
array_two_by_three

# Notice the list above contains two rows and 3 colums - a 2x3 array.

# Here, we can find the shape of our array.

In [ ]:
# Use 'shape' to print the shape of an array.  

array_two_by_three.shape

# The datatype of the items in the array are found using 'dtype'

In [ ]:
# We can also check the type of items in the array
array_one.dtype

# You can use floats and integers in np arrays

In [ ]:
another_array = np.array([4.3, 6.2, 1.1, 3.3])

# print the datatype and 'name' of the value in the array
another_array.dtype.name

# Create an array by filling your chosen 'shape' with ones or zeros.

In [ ]:
# Create and fill this array with zeros, a 2X3 array.
array_with_zeros = np.zeros((2,3))
print(array_with_zeros)

array_with_ones = np.ones((2,3))
print(array_with_ones)

# Create a 3X3 array and fill it with random numbers

In [ ]:
np.random.rand(3,3)

# Create an array and use 'arrange' to fill an array with even numbers from 2 to 20.

In [ ]:
even_array = np.arange(2, 20, 2)
even_array

# Manipulating array elements with basic operations

In [ ]:
# These operations apply to each element in the arrays.

array_one = np.array([10,20,30,40])
array_two = np.array([1, 2, 3,4])

# Subtraction
array_three = array_one - array_two
print(array_three)

# Multiplication
array_four = array_one * array_two
print(array_four)

# Numpy Boolean (True/False)

In [ ]:
array_one = 50
print(array_one > 50)  # is array > 50?  No, so it returns 'False'

print(array_one)

# Matrix multiplication

In [ ]:
array_one = np.array([2,2])
array_two = np.array([4,4])

# To multiply the entire array, use the @ symbol.

np.array_three = array_one @ array_two
print(array_one,array_two)
print(array_three)

# Use 'sum' to sum array elements

In [ ]:
array_one = np.array([1,2,3])

print(array_one.sum())

# Use 'mean' to find the mean of array elements.

In [ ]:
print(array_one.mean())

# Use 'max' to find the max value in an array.

In [ ]:
print(array_three.max())

# Use min to find the minimum value in an array

In [ ]:
print(array_three.min())

# Indexing Arrays

In [ ]:
# One dimensional arrays are similar to lists
array_one = np.array([4,7,1,4])
array_one[3]

# array_one at index three is the value 4

# Integer array indexing

In [ ]:
# Two dimensiona arrays are indexed this way.
array_one = np.array([[1,2], [3, 4]])
print(array_one) # notice the shape and positions of the numbers

# the output is like this [[1 2]
#############             [3 4]]
# to print the 3 in this array, do this:
print(array_one[1,0])  # Remember, the 1 is the row, and the 0 is the column.  So, 1,0 returns the 
                       # value in the spot of row 1, column 0 - which is 3.  Also, remember, Python indexing starts at 0.

# Slicing

In [ ]:
# Slicing allows us to select parts of an array
array_one = np.array([3,4,5,7,9])
print(array_one[:3])  # here we 'slice' out the values from index 0 to index 2.  This can be confusing.
                      #  Just remember that Python indexing goes UP TO the last number, but doesn't include it.  
                      #  For example, index [:3] returns the values in index spots 0,1,2 which are 3,4,5

In [ ]:
# or slice the 2nd and 3rd values with 1:3.  Confused yet?  
print(array_one[1:3])  # This returns the values 4,5. The 4 is in index 1, and the 5 is in index 2.

# Multi dimiensional array indexing

In [ ]:
#multidimensional indexing
array_one = np.array([[3,4,5,6], [7,8,9,10]])
array_one

In [ ]:
# to slice the 1st and 2nd values from the 3rd column which are 5 and 9
print(array_one[0:2,2])  # select 0:2 rows and 2 column.  this slices 5 and 9 out of rows 0,1 and column 2