<a href="https://www.kaggle.com/edwardakalarrywelch/very-basic-pandas-notes?scriptVersionId=87571169" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Very Basic Pandas Notes

# Set Up, Read CSV into DataFrame and Print Header

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('../input/wine-reviews/winemag-data_first150k.csv')
print(df.head(5))

# Note:  This notebook was inspired by a lesson about Pandas by Keith Galli.
#You can see his original lesson on his github page at this address:  https://github.com/KeithGalli/pandas
# He also produces high quality data science videos

# Show Columns

In [ ]:
# Think of a DataFrame as a data structure consisting of rows and columns.  The intersection of each row and column contains an element.
# Here, we show the columns of the DataFrame.  
df.columns

# Viewing Data

In [ ]:
# Here we can view the header of the DataFrame
df.head()

# Use 'tail' to view the last five rows of the DataFrame

In [ ]:
df.tail()

# Use 'index()' to view the index of the DataFrame

In [ ]:
df.index

# Types of Data in a Pandas DataFrame vs a Numpy Array

In [ ]:
# Note:  NumPy arrays have one 'dtype' for the entire array, while Pandas DataFrames have one 'dtype' per column.
# Think of a 'dtype' as a datatype like integer or string, or float, etc.

# To view the data type, use 'dtypes'

In [ ]:
# Keep in mind, df represents the object of the Pandas DataFrame
df.dtypes

# You can use describe() to show quick stats of the DataFrame

In [ ]:
df.describe()

# Select a single column of a DataFrame, yielding a series

In [ ]:
# Here we get the 'country' column of the DataFrame.  Notice how it's accessed in a similar way as Python Dictionaries
df['country']

# Select by label using loc.

In [ ]:
df.loc[:,['country']]  # Here we're telling Pandas we want all rows (:), from the ['country'] column.

# To drop any rows that have missing data, use 'dropna'

In [ ]:
df.dropna(how="any") # This drops any rows in your DataFrame that has any missing values.  This might not be the best option.

# Fill in missing data with 'fillna'

In [ ]:
df.fillna(value=5) # here we fill in any missing values with the value of 5.  This might or might not be a good option, depending on what you're doing.

# Need to know where values are not a number (nan)? us 'isna'

In [ ]:
pd.isna(df) # Here, we create a boolean mask showing which values are numbers of not numbers (nan)